[package]
name = "homebot-ui"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[[bin]]
name = "homebot-ui"
path = "src/main.rs"

[dependencies]
homebot-protocol = { path = "../protocol" }
anyhow = "1"
async-stream = "0.3"
iced = { version = "=0.13.1", default-features = false, features = ["tokio", "tiny-skia", "wgpu", "fira-sans"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "fs"] }
toml = "0.8"
dirs = "5"
